const bbs = {
  menu: ["home", "about", "services", "blog", "contact"],
  bbs_list: {
    1: {
      bbs_pk: 1,
      bbs_title: "제목1",
      bbs_category: "home",
      bbs_content:
        "내용1 내용이 좀 길다면 어떻게될까?내용1 내용이 좀 길다면 어떻게될까?",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    2: {
      bbs_pk: 1,
      bbs_title: "제목1",
      bbs_category: "home",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    3: {
      bbs_pk: 1,
      bbs_title: "제목1",
      bbs_category: "home",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    4: {
      bbs_pk: 1,
      bbs_title: "제목1",
      bbs_category: "home",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    5: {
      bbs_pk: 1,
      bbs_title: "제목1",
      bbs_category: "home",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    6: {
      bbs_pk: 1,
      bbs_title: "제목1",
      bbs_category: "home",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
  },

  bbs_list2: {
    1: {
      bbs_pk: 1,
      bbs_title: "about",
      bbs_category: "about",
      bbs_content:
        "내용1 내용이 좀 길다면 어떻게될까?내용1 내용이 좀 길다면 어떻게될까?",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    2: {
      bbs_pk: 1,
      bbs_title: "about",
      bbs_category: "about",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    3: {
      bbs_pk: 1,
      bbs_title: "about",
      bbs_category: "about",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    4: {
      bbs_pk: 1,
      bbs_title: "about",
      bbs_category: "about",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    5: {
      bbs_pk: 1,
      bbs_title: "about",
      bbs_category: "about",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    6: {
      bbs_pk: 1,
      bbs_title: "about",
      bbs_category: "about",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
  },
  bbs_list3: {
    1: {
      bbs_pk: 1,
      bbs_title: "services",
      bbs_category: "services",
      bbs_content:
        "내용1 내용이 좀 길다면 어떻게될까?내용1 내용이 좀 길다면 어떻게될까?",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    2: {
      bbs_pk: 1,
      bbs_title: "services",
      bbs_category: "services",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    3: {
      bbs_pk: 1,
      bbs_title: "services",
      bbs_category: "services",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    4: {
      bbs_pk: 1,
      bbs_title: "services",
      bbs_category: "services",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    5: {
      bbs_pk: 1,
      bbs_title: "services",
      bbs_category: "services",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
    6: {
      bbs_pk: 1,
      bbs_title: "services",
      bbs_category: "services",
      bbs_content: "내용1",
      bbs_writer: "글쓴이1",
      bbs_date: "2022.01.01",
    },
  },
};
export default bbs;
